[font.normal]
family="JetBrains Mono Nerd Font"

[font]
builtin_box_drawing=true
size=18

[colors.primary]
background="#000000"
foreground="#ffffff"

[colors.normal]
blue="#118fcb"
green="#50C878"
yellow="#FFD700"
magenta="#E0B0FF"
cyan="#40E0D0"
red="#E30B5C"
black="#181818"
white="#E7E7E7"

[colors.bright]
blue="#73C2FB"
green="#90EE90"
yellow="#FFEA00"
magenta="#CCCCFF"
cyan="#7FFFD4"
red="#FF5C5C"
black="#494949"
white="#FFFFFF"
