[window]
opacity = 0.9
[font]
size = 17
[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[colors]
primary.background = "0x1e2127"
primary.foreground = "0xabb2bf"
primary.bright_foreground = "0xe6efff"

# You can uncomment the following section to include cursor colors if needed.
 [colors.cursor]
 text = "0x000000"
 cursor = "0xffffff"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xe6efff"

[colors.dim]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

# The following section for indexed colors can be uncommented if needed.
 [[colors.indexed_colors]]
 index = 16
 color = "0x000000"
